[package]
name = "enumflags2_derive"
version = "0.7.12"
authors = ["maik klein <maikklein@googlemail.com>", "Maja Kądziołka <maya@compilercrim.es>"]
description = "Do not use directly, use the reexport in the `enumflags2` crate. This allows for better compatibility across versions."
license = "MIT OR Apache-2.0"
repository = "https://github.com/meithecatte/enumflags2"
keywords = ["enum", "bitflag", "flag", "bitflags"]
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies.syn]
version = "3.0.3"
features = ["parsing", "printing", "derive", "proc-macro"]
default-features = false

[dependencies]
quote = "1.0.47"
proc-macro2 = "1.0.107"
